name: jamstats

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest] # , ubuntu-latest]
      
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        id: cp310
        with:
          python-version: '3.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          
      - run: echo '${{ steps.cp310.outputs.python-version }}'
      - run: ls ${{ steps.cp310.outputs.python-path }}     
      - run: echo "$Python_ROOT_DIR"
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt pyinstaller
      
      - name: Package Application (windows)
        if: runner.os == 'Windows'
        run:  cd src; pyinstaller ../bin/jamstats --onefile -i ..\resources\jamstats_icon.ico --paths=. --add-data "..\resources\jamstats_logo.png;." --add-data "..\resources\jamstats_version.txt;." --add-data "jamstats\templates;templates" --add-data "jamstats\static;static"; cd .. 
             
      - name: Package Application (linux)
        if: runner.os == 'Linux'
        run:  python -m PyInstaller jamstats.spec
 
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: jamstats-${{ runner.os }}   
          path: src/dist/jamstats.exe
